#!/usr/bin/env bash
# Bash  script transfering a file froma client to a server

if [ "s#" -eq 4 ];
then
scp -i "s4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
