#!/usr/bin/env bash

sudo apt-get-y update
sudo apt-get-y install nginx
HOST_NAME=$(georgeoburu.tech)
HEADER="\\\n\tadd_header X-Server-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z$FIND ]]; then
    sed -i "23i $HEADER"
fi

echo "Hello World!" > /var/www/html/index.html

FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
   sed -i "42i $STRING"
fi
