#!/usr/bin/env bash
# configure a new Haproxy as a load balancer

sudo-get -y update
sudo-get -y install haproxy=1.6.\*

echo '
frontend georgeoburu.tech
	bind 0:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 91661-web-01 54.196.27.62
	server 91661-web-02 100.25.47.209
' >>/etc/haproxy/haproxy.cfg

#Restart Haproxy  service 
service haproxy restart
