#!/usr/bin/env bash
#Script pinging an IP address passed as an argument
#Accept string as argument
#Displays: 5-is_the_host_on_the_network (IP_ADDRESS) if no,
#argument passed
#ping the IP  times

if [ "$#" -lt "1" ]
then
	echo"Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$!" -c 5
fi
