#!/usr/bin/env bash
#Creates a files /var/run/myscript.pid having the script PID
#Displays "To infinity and beyond" indefinitely
#Displays "I hate the kill command" upon receiving a SIFTERM
#Displays the file /var/run/myscript.pid and terminates upon 
#receiving a SIGQUIT and or SIGTERM

terminator() {
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?"' SIGINT
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'terminator' SIGQUIT
done

