#!/usr/bin/env bash
# Bash script that displays
# To infinty and beyond with sleep of 2
# In between each iteration display"I am invicible"

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
