#!/usr/bin/env bash
# Displays numbers from 1 to 100 in a list format
# 	Displays "FizzBuzz" if multiple of 3 and 5
#	Displays "fizz" if a multiple of 3
#	Displays "buzz" if multiple of 5
#	else diplays a number

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
