#!/usr/bin/env bash
#Script displaying contents of the file /etc/passwd

while IFS=':' read -r username password uid gid info home shell; do
    echo "This user $username is part of the $gid gang,"\
	"lives in $home and rides $shell."\
	"${uid}'s place is protectected by the passcode $password,"
	"more info about the user here: $info"
done < "/etc/passwd"
