#!/usr/bin/env bash
#Script displaying numbers from 1 - 20 and displays:
#	4 and "bad luck from italy" for 4th iteration
#	9 and "bad luck from Japan" for 9th iteration
#	17 and "bad luck from Italy" for 17th Iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
