#!/usr/bin/env bash
# Configure a ufw firewall blocking all incoming traffic

sudo apt-get install ufw
sed -i 's/IPV6=. */IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
